CREATE DATABASE employees;

Use employees;

CREATE TABLE employees_details(
  ID INT,
  NAME VARCHAR(20),
  EMAIL VARCHAR(35),
  DOB DATE,
  GENDER CHAR,
  LOCATION VARCHAR(50)
  );
DESCRIBE employees_details;

ALTER TABLE employees_details ADD COLUMN SALARY DECIMAL;
ALTER TABLE employees_details DROP SALARY;
ALTER TABLE employees_details  ADD COLUMN SALARY DECIMAL AFTER DOB; 

ALTER TABLE employees_details RENAME COLUMN LOCATION TO ADDRESS;

ALTER TABLE employees_details MODIFY COLUMN SALARY INT;


CREATE TABLE front_end(
  ID INT,
  NAME VARCHAR(20),
  EMAIL VARCHAR(35),
  DOMAIN VARCHAR(10)
  );
DESCRIBE front_end;

CREATE TABLE back_end(
  ID INT,
  NAME VARCHAR(20),
  EMAIL VARCHAR(35),
  LOCATION VARCHAR(50),
  DOMAIN VARCHAR(10)
  );
DESCRIBE back_end;
